# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Karl Price
email: karuprice@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog/portfolio of Karl Price's study of and search for his first Web Development position, in or around Liverpool, UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Karl_Price
github_username:  karuprice
tagline: "Journey of becoming a Front-End developer, Liverpool UK."

# Build settings           kramdown is a markdown converter
markdown: kramdown
